name: Build and Extract .so files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools-version: 33.0.2

      - name: Build project (assembleDebug)
        run: ./gradlew assembleDebug --stacktrace

      - name: Create directory for extracted .so files
        run: mkdir -p extracted_so_files

      - name: Copy .so files from build to extracted_so_files
        run: |
          # ابحث عن ملفات .so داخل مجلد obj في build وانسخها
          find ./app/build/intermediates/cmake/debug/obj/ -name "*.so" -exec cp {} extracted_so_files/ \; || true
          find ./app/build/intermediates/ndkBuild/debug/obj/ -name "*.so" -exec cp {} extracted_so_files/ \; || true

      - name: List extracted files
        run: ls -la extracted_so_files

      - name: Upload extracted .so files as artifact
        uses: actions/upload-artifact@v3
        with:
          name: extracted-so-files
          path: extracted_so_files/
